version: '3.4'

services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  payment_gateway:
    build:
      context: .
      dockerfile: services/payment-gateway/Dockerfile
    ports:
      - "8080:8080"
  payment_processor:
    build:
      context: .
      dockerfile: services/payment-processor/Dockerfile
    ports:
      - "50051:50051"