@startuml
Title Authorize Sequence Diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 20
actor merchant


box "Payment Gateway"
participant paymentGateway as "payment-gateway"
database payments as paymentsDB
end box
participant issuerGateway as "issuer-gateway"

merchant-> paymentGateway: Authorize
paymentGateway->paymentGateway: validate request
alt invalid request
paymentGateway->merchant: return BadRequest
end alt
paymentGateway->paymentsDB: Create Pending Authorization + action
alt creation fails
paymentGateway<-paymentsDB: return error
paymentGateway->paymentGateway: Return Internal error
paymentGateway->merchant: Return Internal error
end alt
paymentGateway<-paymentsDB: Return OK
paymentGateway-> issuerGateway: CreateIssuerRequest
alt Issuer error
paymentGateway<-issuerGateway: Internal error/ unhandled error
paymentGateway->paymentsDB: Update Payment to Authorized/Declined depending on issuer response
alt DB Write fails
paymentGateway<-paymentsDB: return error
paymentGateway->paymentGateway: log error (trigger alert)
paymentGateway->merchant: return InternalError
end alt
paymentGateway<-paymentsDB: Return ok
paymentGateway->merchant: return InternalError
end alt
paymentGateway<-issuerGateway: Return ok
paymentGateway->paymentsDB: Update Payment to Authorized/Declined depending on issuer response
alt DB Write Fails
paymentGateway<-paymentsDB: return error
paymentGateway->paymentGateway: log error (trigger alert)
paymentGateway->merchant: return 201
end alt
paymentGateway<-paymentsDB: Return ok
paymentGateway->merchant: Return 201
@enduml