@startuml
Title Capture Sequence Diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 20
actor merchant


box "Payment Gateway"
participant paymentGateway as "payment-gateway"
database payments as paymentsDB
end box
participant issuerGateway as "issuer-gateway"

merchant-> paymentGateway: Capture
paymentGateway->paymentGateway: validate request
alt invalid request
paymentGateway->merchant: return BadRequest
end alt

paymentGateway->paymentsDB: GetPayment by ID + actions
alt Payment Not Found
paymentGateway<-paymentsDB: return no record
paymentGateway->merchant: return status 404 (NotFound)
end alt
alt DB Error
paymentGateway<-paymentsDB: return internal error
paymentGateway->merchant: return status 500 (InternalServerError)
end alt
paymentGateway<-paymentsDB: return payment record
paymentGateway->paymentGateway: validate capture against auth
alt Capture exceeds auth amount + existing capture amount/ Payment Refunded/ Voided
 paymentGateway->merchant: return status 422 (UnprocessableEntity)
end alt

paymentGateway-> paymentsDB: Create pending capture action
alt DB Write Fails
paymentGateway<-paymentsDB: return error
paymentGateway->merchant: return InternalError
end
paymentGateway<-paymentsDB: return ok

paymentGateway-> issuerGateway: CreateIssuerRequest - Capture
alt Issuer error
paymentGateway<-issuerGateway: Internal error/ unhandled error
paymentGateway->paymentsDB: Update Action to Declined depending on issuer response
alt DB Write fails
paymentGateway<-paymentsDB: return error
paymentGateway->paymentGateway: log error (trigger alert)
paymentGateway->merchant: return InternalError
end alt
paymentGateway<-paymentsDB: Return ok
paymentGateway->merchant: return InternalError
end alt
paymentGateway<-issuerGateway: Return ok
paymentGateway->paymentsDB: Update Action to Declined depending on issuer response
alt DB Write Fails
paymentGateway<-paymentsDB: return error
paymentGateway->paymentGateway: log error (trigger alert)
paymentGateway->merchant: return 201
end alt
paymentGateway<-paymentsDB: Return ok
paymentGateway->merchant: Return 201

@enduml